### ISSUE TITLE
[FEAT] Creation of the match page

### ISSUE THREAD

**Issue by raygbdias** [CulinarI0/Luna#14]
Is your feature request related to a problem? Please describe.
Currently, our application lacks an interactive matching page that can engage users in a dynamic way. Users need a more interactive and user-friendly interface to answer questions that are crucial for the matching process. The absence of an engaging question interface may lead to lower user engagement and a less personalized experience.

Describe the solution you'd like
The solution involves developing a new matching page that includes a modal pop-up for questions. This modal should appear in an engaging and intuitive manner, prompting users to answer questions essential for the matching algorithm. The design should be clean, user-friendly, and consistent with the application's overall aesthetic. The modal should support various types of questions (e.g., multiple choice, text input) and provide a seamless experience, smoothly transitioning from one question to the next. It's also important to ensure that the modal works well on different devices and screen sizes.

Describe alternatives you've considered
An alternative could be to integrate the questions directly into the matching page without a modal. However, this might clutter the page and overwhelm the user with too much information at once. Another alternative is to use a separate questionnaire page, but this could disrupt the user flow and reduce engagement.

Additional context
The matching page and question modal are key to enhancing user interaction and ensuring more accurate matches. This feature should be designed with user experience as the top priority, considering aspects like ease of use, responsiveness, and minimalism in design. The development team should also consider the technical feasibility and any potential integration issues with the existing backend systems. Mockups or wireframes of the proposed design would be beneficial for further discussion and refinement.

**Comment by GuilhermeFrSaito** [comment]
@raygbdias 
If the user wishes to change any of the answers, how would the user proceed? Will there be an index or would all the questions be on the same page? For this situation, it would be best if the questions were all on the same pages, in my opinion.

**Comment by raygbdias** [comment]
We could have a modal, with the questions, as the user answer a questions it goes to the next one, and so on, if the user wants to change it we can have a button to go back and after the user answers all the questions we can have a final modal with all the questions and answers and ask the user if he wants to change something, otherwise he will press a button and a result will appear
