### ISSUE TITLE
Would it be cool to separate Discover/Recipes into individual items?

### ISSUE THREAD

**Issue by GuilhermeFrSaito** [CulinarI0/Luna#4]
It was detected that Discover and Recipes have diferent purposes, where Recipes would show ready to use Recipes and Discover would direct the user to a more suggestive infos on meals or drinks.

**Comment by raygbdias** [comment]
100% that is an amazing idea, although they are both about recipes, they will have different functionalities

**Comment by edvardsanta** [comment]
So we must define new concepts, what would be "discover" page?
I imagine "discover" is when the user doesn't know what to eat yet and "match" is when the user knows what to eat, but wants an accompaniment to food or drink.
But what do you think @raygbdias?
